### ISSUE TITLE
qx.ui.mobile support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ergobyte/qookery#1]
```
Are you going to support qx.ui.mobile in future?

```

Original issue reported on code.google.com by `alexande...@gmail.com` on 26 Nov 2012 at 9:03

**Comment by gnikolaidis** [comment]
Yes, there are plans for qx.ui.mobile support. In today's release there is a qookerymobile extension project which defines a custom XML namespace and adds components for the mobile version of Qooxdoo widgets.

The current implementation, though very raw and limited, has been used successfully in a QX/Cordova Android/iOS application.
