### ISSUE TITLE
Full 0.6.0 release for contrib compatibility

### ISSUE THREAD

**Issue by cboulanger** [ergobyte/qookery#10]
The way the 0.6.0 release was made somehow doesn't work with the contrib system, which needs a "full release" - it seems like there is only a tag "0.6.0" currently: 
![bildschirmfoto 2019-03-04 um 11 54 30](https://user-images.githubusercontent.com/75390/53729047-70234980-3e74-11e9-9c59-b79a7a0aac03.png)

You might want to integrate `qx contrib publish --version <qookery version>` into your release script to automate this. Simply store `qx config set github.token <your github access token>` first.

**Comment by gnikolaidis** [comment]
Done
