### ISSUE TITLE
ACE Editor: schema demands mode "plain_text" but mode is "text"

### ISSUE THREAD

**Issue by cboulanger** [ergobyte/qookery#12]
In the ACE XSD 
```xml
<attribute name="mode" default="plain_text"><simpleType><restriction base="token">
    ...
    <enumeration value="plain_text" />
    ...
</restriction></simpleType></attribute>
```

However, when using the attribute `mode="plain_text"`, it will result in an error
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (mode-plain_text.js, line 0)`.

There is a file [`mode-text.js`](https://github.com/ajaxorg/ace-builds/blob/32e27226d66b2f3a63d4e393853f84ef3e17a003/src-min/mode-text.js) but I don't think it is necessary to include it. 

It thus seems to me that the XSD is incorrect.

**Comment by gnikolaidis** [comment]
I see that there is a ace/mode/plain_text.js file in the ACE source tree, resulting in build file https://raw.githubusercontent.com/ajaxorg/ace-builds/v1.4.3/src-min/mode-plain_text.js

The error message does not appear when you include above file in the external library directory. Care to investigate further?

**Comment by cboulanger** [comment]
You're right. Closing
