### ISSUE TITLE
Update qookery libraries for new compiler

### ISSUE THREAD

**Issue by cboulanger** [ergobyte/qookery#14]
In order to remove the warnings displayed here:

https://www.qooxdoo.org/qxl.packagebrowser/#ergobyte~qookery~qookery~problems

the `Manifest.json` file of the qookery libraries need to be updated. You can simply run `qx pkg migrate` in the root of each library and it will update it. In order to keep compatibility with version 5/ your previous build pipeline, you might have to re-add the `info.qooxdoo-versions` property afterwards.

**Comment by gnikolaidis** [comment]
Changes seem to pass the schema validation. Not tested with new compiler.
