### ISSUE TITLE
Tutorial needs to be refactored for QooxDoo 3.0 (git head)

### ISSUE THREAD

**Issue by dgtlrift** [ergobyte/qookery#3]
The tutorial uses some constructs which have been deprecated in QooXdoo 3.0 - ie the `"manifest": "https://github.com/ergobyte/qookery/releases/download/0.1/qookery.json"` line and use of `qookery.contexts.Qookery.loadResource` produces warnings.
In the end, the tutorial doesn't seem to work properly.

**Comment by gnikolaidis** [comment]
Thank you for your comment, we will take care of the tutorial update. What kind of warning do you get from `loadResource`? If it is about the synchronous XHR?

**Comment by gnikolaidis** [comment]
The tutorial has been rewritten for upcoming Qooxdoo 6
