### ISSUE TITLE
Tutorial needs to be refactored for QooxDoo 5.0.2

### ISSUE THREAD

**Issue by Level0r0s** [ergobyte/qookery#4]
After changing config.json to

"manifest" : "https://github.com/ergobyte/qookery/releases/download/0.4/qookery.json"

generate.py source-hybrid

----------------------------------------------------------------------------
    Initializing: tutorial
----------------------------------------------------------------------------
>>> Processing configuration
  - Warning: ! Shadowing job "libraries" with local one

----------------------------------------------------------------------------
    Executing: source-hybrid::source-script
----------------------------------------------------------------------------
>>> Scanning libraries  <type 'exceptions.RuntimeError'> :
Contrib URIs (starting with 'contrib://', 'http://' or 'https://') are no longer supported. Find the download locations of those in the contrib catalog and down
load them manually. Then point to the 'Manifest.json' files with local filepaths.

any information to correct this error?

Tanks

Cristiano

**Comment by Level0r0s** [comment]
Resolved.

change
                    "manifest": "https://github.com/ergobyte/qookery/releases/download/0.1/qookery.json"
to
                   "manifest" : "../lib/qookery/qookery/Manifest.json"

change
                  qookery.contexts.Qookery.openWindow("tutorial/forms/window.xml");
to
          qookery.contexts.Qookery.openWindow("resource/tutorial/forms/window.xml");

**Comment by gnikolaidis** [comment]
The tutorial has been rewritten for upcoming Qooxdoo 6
