### ISSUE TITLE
ACE Editor: support autocomplete

### ISSUE THREAD

**Issue by cboulanger** [ergobyte/qookery#9]
https://github.com/ajaxorg/ace/wiki/How-to-enable-Autocomplete-in-the-Ace-editor

**Comment by gnikolaidis** [comment]
Can you please check that the latest commit on master does the trick? It worked for us quite well.

**Comment by cboulanger** [comment]
cool! I will try tonight and give you feedback.

**Comment by gnikolaidis** [comment]
You will have to download `ext-language_tools.js` into your `/lib/ace/` directory and add `auto-complete="basic"` to the XML element

**Comment by cboulanger** [comment]
Thanks. That could be a handy addition to the Qookery demo, too. I don't know how well the autocomplete mechanism can handle nested xml, though...

**Comment by cboulanger** [comment]
No luck yet. This is what I have:

https://github.com/cboulanger/eventrecorder/blob/master/source/class/cboulanger/eventrecorder/UiController.js#L564
https://github.com/cboulanger/eventrecorder/blob/master/source/resource/cboulanger/eventrecorder/forms/editor.xml#L123

No errors, but the `console.log` in [Line 587](https://github.com/cboulanger/eventrecorder/blob/master/source/class/cboulanger/eventrecorder/UiController.js#L587) is never called. Did I forget something?

**Comment by cboulanger** [comment]
With #13, it works for me, too.

**Comment by cboulanger** [comment]
With the latest changes in Master, it works as expected. Thank you very much.

**Comment by cboulanger** [comment]
It's working very well!

Would you consider releasing the autocomplete support in current master in a patch release so that I can use the contrib system for the travis script and so that I don't have to require users to clone master?

That would be wonderful!
Christian

**Comment by gnikolaidis** [comment]
Sure thing, I just made a 0.7.0 pre-release.
